"""新增相關法規資料表

Revision ID: 3109808c5e87
Revises: aebb5a81efed
Create Date: 2024-10-12 15:19:25.019697

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '3109808c5e87'
down_revision: Union[str, None] = 'aebb5a81efed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('document',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('category', sa.Enum('ALL', 'DEPARTMENT_LAWS', 'COMMERCIAL_LAW', 'TAX_RELATED_LAWS', 'DONATION_FORMS_DOWNLOAD', name='documentcategory'), nullable=False),
    sa.Column('description_link', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('document')
    # ### end Alembic commands ###
