"""新增匯入日期欄位

Revision ID: 59837a8da896
Revises: ed68c67a0e79
Create Date: 2024-10-10 17:01:30.224400

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '59837a8da896'
down_revision: Union[str, None] = 'ed68c67a0e79'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donations', sa.Column('input_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donations', 'input_date')
    # ### end Alembic commands ###
