"""init migration

Revision ID: 5a7286d1450a
Revises:
Create Date: 2024-10-10 20:18:26.310029

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5a7286d1450a'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('unit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donationpurpose',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('lump_sum', sa.Integer(), nullable=False),
    sa.Column('summary', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('news',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('is_show', sa.Boolean(), nullable=False),
    sa.Column('unit_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['unit_id'], ['unit.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('donations',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('user_birthday', sa.Date(), nullable=False),
    sa.Column('id_card', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('phone_number', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('email', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('identity', sa.Enum('ALUMNI', 'STAFF', 'PARENT', 'COMMUNITY', 'CORPORATION', 'OTHER', name='donortype'), nullable=False),
    sa.Column('year', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('gept', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('res_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('registered_address', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('public_status', sa.Enum('PUBLIC', 'ANONYMOUS', 'PARTIALLY', name='pubicstatus'), nullable=False),
    sa.Column('memo', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('amount', sa.Integer(), nullable=False),
    sa.Column('account', sqlmodel.sql.sqltypes.AutoString(), nullable=False),
    sa.Column('type', sa.Enum('STORE', 'BANK', name='donationtype'), nullable=False),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('transaction_id', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('input_date', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('purpose_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['purpose_id'], ['donationpurpose.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('donations')
    op.drop_table('news')
    op.drop_table('donationpurpose')
    op.drop_table('user')
    op.drop_table('unit')
    # ### end Alembic commands ###
