"""new_table_VulenrabilityThreat

Revision ID: 869f760a4a9c
Revises: c2cc04916446
Create Date: 2024-09-12 15:27:32.433091

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '869f760a4a9c'
down_revision: Union[str, None] = 'c2cc04916446'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('vulnerabilitythreat',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vulnerability_name', sqlmodel.sql.sqltypes.AutoString(length=255), nullable=False),
    sa.Column('threat_type', sqlmodel.sql.sqltypes.AutoString(length=100), nullable=True),
    sa.Column('default_severity', sa.Integer(), nullable=True),
    sa.Column('assessment_criteria', sqlmodel.sql.sqltypes.AutoString(), nullable=True),
    sa.Column('cia_confidentiality', sa.Boolean(), nullable=False),
    sa.Column('cia_integrity', sa.Boolean(), nullable=False),
    sa.Column('cia_availability', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerabilitythreat')
    # ### end Alembic commands ###
