"""修改 donation_purpose 欄位名稱

Revision ID: aebb5a81efed
Revises: 5a7286d1450a
Create Date: 2024-10-12 14:21:15.931496

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'aebb5a81efed'
down_revision: Union[str, None] = '5a7286d1450a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donationpurpose', sa.Column('title', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.add_column('donationpurpose', sa.Column('description', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('donationpurpose', 'name')
    op.drop_column('donationpurpose', 'summary')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('donationpurpose', sa.Column('summary', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.add_column('donationpurpose', sa.Column('name', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('donationpurpose', 'description')
    op.drop_column('donationpurpose', 'title')
    # ### end Alembic commands ###
