"""Add team to Hero

Revision ID: c4c8e568addf
Revises: 7ecac4942b35
Create Date: 2024-09-11 23:40:20.654281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'c4c8e568addf'
down_revision: Union[str, None] = '7ecac4942b35'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hero', sa.Column('team', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('hero', 'team')
    # ### end Alembic commands ###
