"""initial migration

Revision ID: cb633635ef2e
Revises: 
Create Date: 2024-09-21 00:45:06.147333

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'cb633635ef2e'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vulnerabilitythreat')
    op.drop_table('asset')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('asset',
    sa.Column('asset_id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('asset_name', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_type', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('owner', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('location', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('classification_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('risk_level', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('creation_date', postgresql.TIMESTAMP(), autoincrement=False, nullable=False),
    sa.Column('status', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('asset_value', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=True),
    sa.Column('vendor', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('lifetime', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('notes', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('asset_id', name='asset_pkey')
    )
    op.create_table('vulnerabilitythreat',
    sa.Column('id', sa.INTEGER(), autoincrement=True, nullable=False),
    sa.Column('vulnerability_name', sa.VARCHAR(length=255), autoincrement=False, nullable=False),
    sa.Column('threat_type', sa.VARCHAR(length=100), autoincrement=False, nullable=True),
    sa.Column('default_severity', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('assessment_criteria', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('cia_confidentiality', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cia_integrity', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('cia_availability', sa.BOOLEAN(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=True),
    sa.PrimaryKeyConstraint('id', name='vulnerabilitythreat_pkey')
    )
    # ### end Alembic commands ###
