"""添加 image url 欄位

Revision ID: dd01d2d8a68e
Revises: 0503b8def55b
Create Date: 2024-10-20 22:29:56.046558

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'dd01d2d8a68e'
down_revision: Union[str, None] = '0503b8def55b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('announcement', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('donationpurpose', sa.Column('image_url', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('donationpurpose', 'image_url')
    op.drop_column('announcement', 'image_url')
    # ### end Alembic commands ###
