// This file is auto-generated by @hey-api/openapi-ts

export const AddressDataSchema = {
    properties: {
        address: {
            type: 'string',
            title: 'Address',
            example: '臺中市西屯區臺灣大道三段99號'
        }
    },
    type: 'object',
    required: ['address'],
    title: 'AddressData',
    description: `用於創建 Address 記錄的 schema，
包含地址需要提交的所有字段。`
} as const;

export const AnnouncementSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url',
            description: 'S3 圖片的 URL 或相對路徑'
        },
        unit_id: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['date', 'title', 'description', 'is_show'],
    title: 'Announcement'
} as const;

export const AnnouncementCreateSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        unit_id: {
            type: 'integer',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['date', 'title', 'description', 'is_show', 'unit_id'],
    title: 'AnnouncementCreate',
    description: `用於創建 Announcement 記錄的 schema，
包含公告需要提交的所有字段。`
} as const;

export const AnnouncementInfoSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        unit: {
            '$ref': '#/components/schemas/UnitInfo'
        }
    },
    type: 'object',
    required: ['date', 'title', 'description', 'is_show', 'id', 'unit'],
    title: 'AnnouncementInfo',
    description: `用於返回 New 的基本信息，
適用於讀取操作。`
} as const;

export const AnnouncementUpdateSchema = {
    properties: {
        date: {
            type: 'string',
            format: 'date',
            title: 'Date'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        unit_id: {
            type: 'integer',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['date', 'title', 'description', 'is_show', 'id', 'unit_id'],
    title: 'AnnouncementUpdate',
    description: `用於更新 Announcement 記錄的 schema，
允許公告更新。`
} as const;

export const AuthRequestSchema = {
    properties: {
        code: {
            type: 'string',
            title: 'Code'
        }
    },
    type: 'object',
    required: ['code'],
    title: 'AuthRequest'
} as const;

export const AuthResponseSchema = {
    properties: {
        access_token: {
            type: 'string',
            title: 'Access Token'
        }
    },
    type: 'object',
    required: ['access_token'],
    title: 'AuthResponse'
} as const;

export const BarCodeDataSchema = {
    properties: {
        Group: {
            type: 'string',
            title: 'Group',
            example: '730044'
        },
        SerialNumber: {
            type: 'string',
            title: 'Serialnumber',
            example: '00001'
        },
        Time: {
            type: 'string',
            title: 'Time',
            example: '9991230'
        },
        Money: {
            type: 'string',
            title: 'Money',
            example: '1000'
        }
    },
    type: 'object',
    required: ['Group', 'SerialNumber', 'Time', 'Money'],
    title: 'BarCodeData',
    description: `用於創建 BarCode 記錄的 schema，
包含 BarCode 需要提交的所有字段。`
} as const;

export const DonationSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        username: {
            type: 'string',
            title: 'Username'
        },
        user_birthday: {
            type: 'string',
            format: 'date',
            title: 'User Birthday'
        },
        id_card: {
            type: 'string',
            title: 'Id Card'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        identity: {
            '$ref': '#/components/schemas/DonorType',
            description: '捐款者身分',
            default: '校友'
        },
        year: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        gept: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gept'
        },
        res_address: {
            type: 'string',
            title: 'Res Address'
        },
        registered_address: {
            type: 'string',
            title: 'Registered Address'
        },
        public_status: {
            '$ref': '#/components/schemas/PubicStatus',
            description: '公開狀態',
            default: '公開'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        account: {
            type: 'string',
            title: 'Account'
        },
        type: {
            '$ref': '#/components/schemas/DonationType',
            description: '捐款方式',
            default: '實體店支付'
        },
        transaction_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Id'
        },
        input_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Date'
        },
        purpose_id: {
            type: 'integer',
            title: 'Purpose Id'
        }
    },
    type: 'object',
    required: ['username', 'user_birthday', 'id_card', 'phone_number', 'email', 'res_address', 'registered_address', 'amount', 'account'],
    title: 'Donation'
} as const;

export const DonationPurposeSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        lump_sum: {
            type: 'integer',
            title: 'Lump Sum'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url',
            description: 'S3 圖片的 URL 或相對路徑'
        },
        unit_id: {
            type: 'integer',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['title', 'lump_sum', 'description', 'is_show'],
    title: 'DonationPurpose'
} as const;

export const DonationPurposeCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        lump_sum: {
            type: 'integer',
            title: 'Lump Sum'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        unit_id: {
            type: 'integer',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['title', 'lump_sum', 'description', 'is_show', 'unit_id'],
    title: 'DonationPurposeCreate',
    description: `用於創建 DonationPurpose 紀錄的 schema。
包含捐款目的提交的所有必要字段。`
} as const;

export const DonationPurposeInfoSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        description: {
            type: 'string',
            title: 'Description'
        }
    },
    type: 'object',
    required: ['title', 'description'],
    title: 'DonationPurposeInfo',
    description: `用於返回 Donation 的子模型，
適用於讀取操作。`
} as const;

export const DonationPurposeUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        lump_sum: {
            type: 'integer',
            title: 'Lump Sum'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        unit_id: {
            type: 'integer',
            title: 'Unit Id'
        }
    },
    type: 'object',
    required: ['title', 'lump_sum', 'description', 'is_show', 'unit_id'],
    title: 'DonationPurposeUpdate',
    description: `用於更新 DonationPurpose 的 schema，
允許捐款目的更新。`
} as const;

export const DonationTypeSchema = {
    type: 'string',
    enum: ['實體店支付', '銀行支付'],
    title: 'DonationType',
    description: `表示捐款方式的 Enum。

STORE: 使用實體店支付。
BANK: 使用銀行支付。`
} as const;

export const DonationUpdateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        user_birthday: {
            type: 'string',
            format: 'date',
            title: 'User Birthday'
        },
        id_card: {
            type: 'string',
            title: 'Id Card'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        identity: {
            '$ref': '#/components/schemas/DonorType',
            default: '校友'
        },
        year: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        gept: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gept'
        },
        res_address: {
            type: 'string',
            title: 'Res Address'
        },
        registered_address: {
            type: 'string',
            title: 'Registered Address'
        },
        public_status: {
            '$ref': '#/components/schemas/PubicStatus',
            default: '公開'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        account: {
            type: 'string',
            title: 'Account'
        },
        type: {
            '$ref': '#/components/schemas/DonationType',
            default: '實體店支付'
        },
        transaction_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Id'
        },
        input_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Date'
        },
        purpose_id: {
            type: 'integer',
            title: 'Purpose Id'
        }
    },
    type: 'object',
    required: ['username', 'user_birthday', 'id_card', 'phone_number', 'email', 'res_address', 'registered_address', 'amount', 'account', 'purpose_id'],
    title: 'DonationUpdate',
    description: `用於更新 Donation 的 schema，
允許捐款更新。`
} as const;

export const DonationsCreateSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        user_birthday: {
            type: 'string',
            format: 'date',
            title: 'User Birthday'
        },
        id_card: {
            type: 'string',
            title: 'Id Card'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        identity: {
            '$ref': '#/components/schemas/DonorType',
            default: '校友'
        },
        year: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        gept: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gept'
        },
        res_address: {
            type: 'string',
            title: 'Res Address'
        },
        registered_address: {
            type: 'string',
            title: 'Registered Address'
        },
        public_status: {
            '$ref': '#/components/schemas/PubicStatus',
            default: '公開'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        account: {
            type: 'string',
            title: 'Account'
        },
        type: {
            '$ref': '#/components/schemas/DonationType',
            default: '實體店支付'
        },
        transaction_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Id'
        },
        input_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Date'
        },
        purpose_id: {
            type: 'integer',
            title: 'Purpose Id'
        }
    },
    type: 'object',
    required: ['username', 'user_birthday', 'id_card', 'phone_number', 'email', 'res_address', 'registered_address', 'amount', 'account', 'purpose_id'],
    title: 'DonationsCreate',
    description: `用於創建 Donations 記錄的 schema，
包含用戶需要提交的所有字段。`
} as const;

export const DonorTypeSchema = {
    type: 'string',
    enum: ['校友', '教職員', '家長', '社區成員', '公司', '其他'],
    title: 'DonorType',
    description: `表示捐款者身份的 Enum。

ALUMNI: 校友
STAFF: 教職員
PARENT: 家長
COMMUNITY: 社區成員
CORPORATION: 公司
OTHER: 其他`
} as const;

export const HTTPValidationErrorSchema = {
    properties: {
        detail: {
            items: {
                '$ref': '#/components/schemas/ValidationError'
            },
            type: 'array',
            title: 'Detail'
        }
    },
    type: 'object',
    title: 'HTTPValidationError'
} as const;

export const PaginatedAnnouncementInfoResponseSchema = {
    properties: {
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/AnnouncementInfo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total_count', 'items'],
    title: 'PaginatedAnnouncementInfoResponse',
    description: `用於返回分頁的 New 的基本信息，
適用於讀取操作，可返回總筆數。`
} as const;

export const PaginatedRegulationInfoResponseSchema = {
    properties: {
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/RegulationInfo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total_count', 'items'],
    title: 'PaginatedRegulationInfoResponse',
    description: `用於返回分頁的 Regulation 的基本信息，
適用於讀取操作，可返回總筆數。`
} as const;

export const PubicStatusSchema = {
    type: 'string',
    enum: ['公開', '匿名', '匿名但受捐單位知曉'],
    title: 'PubicStatus',
    description: `表示公開狀態的 Enum。

PUBLIC: 公開
ANONYMOUS: 匿名
PARTIALLY: 匿名但受捐單位知曉`
} as const;

export const RegulationSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/RegulationCategory',
            description: '相關法規類別',
            default: 'ALL'
        },
        description_link: {
            type: 'string',
            title: 'Description Link'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        }
    },
    type: 'object',
    required: ['title', 'description_link', 'is_show'],
    title: 'Regulation'
} as const;

export const RegulationCategorySchema = {
    type: 'string',
    enum: ['ALL', 'DEPARTMENT_LAWS', 'COMMERCIAL_LAW', 'TAX_RELATED_LAWS', 'DONATION_FORMS_DOWNLOAD'],
    title: 'RegulationCategory',
    description: `表示相關法規方式的 Enum。

ALL: 全部
DEPARTMENT_LAWS: 各部法規
COMMERCIAL_LAW: 北商大法規
TAX_RELATED_LAWS: 相關稅法
DONATION_FORMS_DOWNLOAD: 捐款相關表單下載`
} as const;

export const RegulationCreateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/RegulationCategory',
            default: 'ALL'
        },
        description_link: {
            type: 'string',
            title: 'Description Link'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        }
    },
    type: 'object',
    required: ['title', 'description_link', 'is_show'],
    title: 'RegulationCreate',
    description: `用於創建 Regulationt 記錄的 schema，
包含用戶提交的所有必要字段。`
} as const;

export const RegulationInfoSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/RegulationCategory',
            default: 'ALL'
        },
        description_link: {
            type: 'string',
            title: 'Description Link'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['title', 'description_link', 'is_show', 'id'],
    title: 'RegulationInfo',
    description: `用於返回 Regulation 的基本信息，
適用於讀取操作。`
} as const;

export const RegulationtUpdateSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        category: {
            '$ref': '#/components/schemas/RegulationCategory',
            default: 'ALL'
        },
        description_link: {
            type: 'string',
            title: 'Description Link'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        }
    },
    type: 'object',
    required: ['title', 'description_link', 'is_show'],
    title: 'RegulationtUpdate',
    description: `用於更新 Regulationt 記錄的 schema，
允許法規更新。`
} as const;

export const UnitSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'Unit'
} as const;

export const UnitCreateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'UnitCreate',
    description: `用於創建 Unit 記錄的 schema，
包含單位提交的所有必要字段。`
} as const;

export const UnitInfoSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['name', 'id'],
    title: 'UnitInfo',
    description: '用於返回 Unit 的基本信息，適用於讀取操作。'
} as const;

export const UnitUpdateSchema = {
    properties: {
        name: {
            type: 'string',
            title: 'Name'
        }
    },
    type: 'object',
    required: ['name'],
    title: 'UnitUpdate',
    description: `用於更新 Unit 記錄的 schema，
允許單位更新。`
} as const;

export const UserSchema = {
    properties: {
        id: {
            type: 'integer',
            title: 'Id'
        },
        account: {
            type: 'string',
            title: 'Account'
        }
    },
    type: 'object',
    required: ['account'],
    title: 'User'
} as const;

export const UserCreateSchema = {
    properties: {
        account: {
            type: 'string',
            title: 'Account'
        }
    },
    type: 'object',
    required: ['account'],
    title: 'UserCreate',
    description: `用於創建 User 記錄的 schema，
包含用戶提交的所有必要字段。`
} as const;

export const ValidationErrorSchema = {
    properties: {
        loc: {
            items: {
                anyOf: [
                    {
                        type: 'string'
                    },
                    {
                        type: 'integer'
                    }
                ]
            },
            type: 'array',
            title: 'Location'
        },
        msg: {
            type: 'string',
            title: 'Message'
        },
        type: {
            type: 'string',
            title: 'Error Type'
        }
    },
    type: 'object',
    required: ['loc', 'msg', 'type'],
    title: 'ValidationError'
} as const;

export const app__application__admin__schemas__donation__DonationInfoSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        user_birthday: {
            type: 'string',
            format: 'date',
            title: 'User Birthday'
        },
        id_card: {
            type: 'string',
            title: 'Id Card'
        },
        phone_number: {
            type: 'string',
            title: 'Phone Number'
        },
        email: {
            type: 'string',
            title: 'Email'
        },
        identity: {
            '$ref': '#/components/schemas/DonorType',
            default: '校友'
        },
        year: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Year'
        },
        gept: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Gept'
        },
        res_address: {
            type: 'string',
            title: 'Res Address'
        },
        registered_address: {
            type: 'string',
            title: 'Registered Address'
        },
        public_status: {
            '$ref': '#/components/schemas/PubicStatus',
            default: '公開'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        account: {
            type: 'string',
            title: 'Account'
        },
        type: {
            '$ref': '#/components/schemas/DonationType',
            default: '實體店支付'
        },
        status: {
            anyOf: [
                {
                    type: 'integer'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Status'
        },
        transaction_id: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Transaction Id'
        },
        input_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Date'
        },
        id: {
            type: 'integer',
            title: 'Id'
        },
        purpose_id: {
            type: 'integer',
            title: 'Purpose Id'
        }
    },
    type: 'object',
    required: ['username', 'user_birthday', 'id_card', 'phone_number', 'email', 'res_address', 'registered_address', 'amount', 'account', 'id', 'purpose_id'],
    title: 'DonationInfo',
    description: `用於返回 Donations 的基本信息，
適用於讀取操作。`
} as const;

export const app__application__admin__schemas__donation__PaginatedDonationInfoResponseSchema = {
    properties: {
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/app__application__admin__schemas__donation__DonationInfo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total_count', 'items'],
    title: 'PaginatedDonationInfoResponse',
    description: `用於返回分頁的 Donation 的基本信息，
適用於讀取操作，可返回總筆數。`
} as const;

export const app__application__admin__schemas__donation_purpose__DonationPurposeItemSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        lump_sum: {
            type: 'integer',
            title: 'Lump Sum'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['title', 'lump_sum', 'description', 'is_show', 'id'],
    title: 'DonationPurposeItem',
    description: '用於返回 DonationPurpose 的基本信息，適用於讀取操作。'
} as const;

export const app__application__admin__schemas__donation_purpose__PaginatedDonationPurposeInfoResponseSchema = {
    properties: {
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/app__application__admin__schemas__donation_purpose__DonationPurposeItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total_count', 'items'],
    title: 'PaginatedDonationPurposeInfoResponse',
    description: `用於返回分頁的 DonationPurpose 的基本信息，
適用於讀取操作，可返回總筆數。`
} as const;

export const app__application__client__schemas__donation__DonationInfoSchema = {
    properties: {
        username: {
            type: 'string',
            title: 'Username'
        },
        amount: {
            type: 'integer',
            title: 'Amount'
        },
        input_date: {
            anyOf: [
                {
                    type: 'string',
                    format: 'date'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Input Date'
        },
        purpose: {
            '$ref': '#/components/schemas/DonationPurposeInfo'
        }
    },
    type: 'object',
    required: ['username', 'amount', 'purpose'],
    title: 'DonationInfo',
    description: `用於返回 Donations 的基本信息，
適用於讀取操作。`
} as const;

export const app__application__client__schemas__donation__PaginatedDonationInfoResponseSchema = {
    properties: {
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/app__application__client__schemas__donation__DonationInfo'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total_count', 'items'],
    title: 'PaginatedDonationInfoResponse',
    description: `用於返回分頁的 Donation 的基本信息，
適用於讀取操作，可返回總筆數。`
} as const;

export const app__application__client__schemas__donation_purpose__DonationPurposeItemSchema = {
    properties: {
        title: {
            type: 'string',
            title: 'Title'
        },
        lump_sum: {
            type: 'integer',
            title: 'Lump Sum'
        },
        description: {
            type: 'string',
            title: 'Description'
        },
        memo: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Memo'
        },
        is_show: {
            type: 'boolean',
            title: 'Is Show'
        },
        image_url: {
            anyOf: [
                {
                    type: 'string'
                },
                {
                    type: 'null'
                }
            ],
            title: 'Image Url'
        },
        total_donation: {
            type: 'number',
            title: 'Total Donation'
        },
        achieved_percentage: {
            type: 'number',
            title: 'Achieved Percentage'
        },
        id: {
            type: 'integer',
            title: 'Id'
        }
    },
    type: 'object',
    required: ['title', 'lump_sum', 'description', 'is_show', 'total_donation', 'achieved_percentage', 'id'],
    title: 'DonationPurposeItem',
    description: '用於返回 DonationPurpose 的基本信息，適用於讀取操作。'
} as const;

export const app__application__client__schemas__donation_purpose__PaginatedDonationPurposeInfoResponseSchema = {
    properties: {
        total_count: {
            type: 'integer',
            title: 'Total Count'
        },
        items: {
            items: {
                '$ref': '#/components/schemas/app__application__client__schemas__donation_purpose__DonationPurposeItem'
            },
            type: 'array',
            title: 'Items'
        }
    },
    type: 'object',
    required: ['total_count', 'items'],
    title: 'PaginatedDonationPurposeInfoResponse',
    description: `用於返回分頁的 DonationPurpose 的基本信息，
適用於讀取操作，可返回總筆數。`
} as const;