name: Docker Compose Deployment on Self-Hosted Runner

on:
  pull_request:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy Using Docker Compose
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create and deploy using Docker Compose
        run: |
          cat <<EOF > ./backend/.env
          APP_NAME=${{ secrets.APP_NAME }}
          ADMIN_EMAIL=${{ secrets.ADMIN_EMAIL }}
          ITEMS_PER_USER=${{ secrets.ITEMS_PER_USER }}
          BARCODE_API_URL=${{ secrets.BARCODE_API_URL }}
          ZIPCODE_API_URL=${{ secrets.ZIPCODE_API_URL }}
          ENABLE_DOCS=${{ secrets.ENABLE_DOCS }}
          POSTGRES_USER=${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD=${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_HOST=${{ secrets.POSTGRES_HOST }}
          POSTGRES_PORT=${{ secrets.POSTGRES_PORT }}
          POSTGRES_DB=${{ secrets.POSTGRES_DB }}
          GOOGLE_REDIRECT_URI=${{ secrets.GOOGLE_REDIRECT_URI }}
          GOOGLE_CLIENT_ID=${{ secrets.GOOGLE_CLIENT_ID }}
          GOOGLE_CLIENT_SECRET=${{ secrets.GOOGLE_CLIENT_SECRET }}
          SIGNING_KEY=${{ secrets.SIGNING_KEY }}
          FTP_HOST=${{ secrets.FTP_HOST }}
          FTP_USER=${{ secrets.FTP_USER }}
          FTP_PASSWORD=${{ secrets.FTP_PASSWORD }}
          FTP_PORT=${{ secrets.FTP_PORT }}
          EOF
          docker-compose up --build -d

      - name: Verify Deployment
        run: |
          echo "Listing running containers..."
          docker ps

      - name: Cleanup on Failure
        if: ${{ failure() }}
        run: docker-compose down
        continue-on-error: true
