name: Build and Upload Artifacts

on:
  pull_request:
    branches:
      - develop
      - main

jobs:
  build-and-upload:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install dependencies
        working-directory: ./frontend
        run: npm install

      - name: Run ESLint
        working-directory: ./frontend
        run: npm run lint

      - name: Build admin
        working-directory: ./frontend
        run: npm run build-admin

      - name: Build client
        working-directory: ./frontend
        run: npm run build-client

      - name: Create tar.gz file of frontend and backend
        run: |
          tar -czf build_artifacts.tar.gz frontend/app/admin/dist frontend/app/client/dist backend

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: build-artifacts
          path: build_artifacts.tar.gz

  release:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    needs: build-and-upload

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Create GitHub Release
        id: create_release
        uses: actions/create-release@v1
        with:
          tag_name: ${{ github.sha }}
          release_name: "Release ${{ github.sha }}"
          body: "Release for commit ${{ github.sha }}"
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload tar.gz to Release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build_artifacts.tar.gz
          asset_name: build_artifacts.tar.gz
          asset_content_type: application/gzip
